#Этап 1 - Копирование файлов
FROM python:3.12-slim AS builder
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000

#Этап 2 - Запускаем приложение с помощью uvicorn, делая его доступным по сети
FROM builder
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
